### ISSUE TITLE
Bump wallabag-api 

### ISSUE THREAD

**Issue by bilelmoussaoui** [swalladge/wallabag-api#4]
Currently, the latest release doesn't build 
```
error[E0252]: the name `Deserialize` is defined multiple times
 --> /home/bilelmoussaoui/Projects/reading-list/_build/target/cargo-CARGO_HOME/registry/src/github.com-1ecc6299db9ec823/wallabag-api-0.1.1/src/utils/serde.rs:6:5
  |
5 | use serde::{Deserialize, Deserializer, Serializer};
  |             ----------- previous import of the macro `Deserialize` here
6 | use serde_derive::Deserialize;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ `Deserialize` reimported here
  |
  = note: `Deserialize` must be defined only once in the macro namespace of this module
```
It was already fixed in master but not released yet. Thanks!

**Comment by swalladge** [comment]
Thanks for reporting this! I will cut a new release when I have time on the weekend.

Also thanks for your interest in the project! Please feel free to report any design issues or feature requests. Happy to make breaking changes (while it's not v1 yet) if it means improving the usability of the api. :)

**Comment by bilelmoussaoui** [comment]
I'm currently using it to write a GTK frontend so I will probably report some other bugs/send some merge requests

**Comment by swalladge** [comment]
Awesome! Let me know if you open-source it. I've been thinking about building a proper frontend for ages and would be keen on contributing. :smile:

**Comment by bilelmoussaoui** [comment]
It's already open source. The source code is here https://gitlab.gnome.org/bilelmoussaoui/read-it-later. Please ping me somewhere so we can discuss how we can work on this

**Comment by swalladge** [comment]
@bilelmoussaoui v0.1.2  published to crates.io :smile:
