### ISSUE TITLE
Make the paginated entries public

### ISSUE THREAD

**Issue by bilelmoussaoui** [swalladge/wallabag-api#6]
In the context of Read It Later; the get_entries in some cases could lead to loading a thousands of hundreds of articles. In order to avoid making the app unusable for a few minutes my plan is to only load a few articles and load  the rest in the background and load them only if they are requested (on scroll).

Allowing to fetch paginated entries makes completely sense to have here to benefit other clients

**Comment by swalladge** [comment]
@bilelmoussaoui did you have ideas for the api? I was thinking of something like:

```
struct PaginationArgs {
  page: u32,
  n_per_page: enum(default, 20, 50, etc...),
}

struct Page {
  entries: Entries,
  page: u32,
  n_pages: u32, // total number of pages available
  n_per_page: enum(default, 20, 50, etc...),
}

get_entries_page(self, filter: EntriesFilter, page: PaginationArgs) -> CLientResult<Page> { ... }
```

**Comment by bilelmoussaoui** [comment]
That looks good to me, I think we can go with that and I will give some feedback once I have implemented it in Read It later? :)
