### ISSUE TITLE
Switch to surf from reqwest

### ISSUE THREAD

**Issue by swalladge** [swalladge/wallabag-api#9]
- surf is smaller, lighter, and works with non-tokio async executors

**Comment by vorot93** [comment]
surf is definitely not lighter or faster since its backend is a C library as compared to reqwest (100% Rust).

**Comment by swalladge** [comment]
@vorot93 not sure if you're trolling, annoyed that I dropped reqwest, or have some use case for this library where surf is not optimal. 

I switched to surf on advice from a developer who is (afaik) the only one actively using this in a public project. If you are also using the library and have a use case and/or request, please let me know.

**Comment by vorot93** [comment]
You know that this is a public repo and you did drop a line of FUD in issue description, right? If it wasn't there I wouldn't have responded.

**Comment by swalladge** [comment]
@vorot93 Fair enough, description updated for accuracy.
